// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package jobs

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID        uuid.UUID          `json:"id"`
	ClientID  uuid.UUID          `json:"clientId"`
	Title     pgtype.Text        `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}
