// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package projects

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID            uuid.UUID
	EmbeddingsIds []uuid.UUID
	Filename      string
	Title         *string
	ProjectID     uuid.UUID
	CreatedAt     time.Time
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	ClientID  uuid.UUID `json:"client_id"`
	Title     *string   `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

type SchemaMigration struct {
	Version string
}
