services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      - POSTGRES_DB=pivo
      - POSTGRES_USER=pivo
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ../db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  chromadb:
    image: chromadb/chroma:0.6.2
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - 8000:8000
volumes:
  postgres_data:
  chroma-data:
