// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package documents

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID            uuid.UUID
	EmbeddingsIds []uuid.UUID
	Filename      string
	Title         *string
	ProjectID     uuid.UUID
	CreatedAt     time.Time
}

type Project struct {
	ID        uuid.UUID
	ClientID  uuid.UUID
	Title     *string
	CreatedAt time.Time
}

type SchemaMigration struct {
	Version string
}
