// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package documents

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID            uuid.UUID   `json:"id"`
	EmbeddingsIds []uuid.UUID `json:"embeddingsIds"`
	Filename      string      `json:"filename"`
	Title         *string     `json:"title"`
	ProjectID     uuid.UUID   `json:"projectId"`
	CreatedAt     time.Time   `json:"createdAt"`
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	ClientID  uuid.UUID `json:"clientId"`
	Title     *string   `json:"title"`
	CreatedAt time.Time `json:"createdAt"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}
